version: '3'

services:
  redis:
    image: 'redis'
    networks: ['default', 'smart-scavenger-hunt']

  lrid-generator:
    image: 'afloury/smart-scavenger-hunt:lrid-generator'
    networks: ['default', 'smart-scavenger-hunt']
    depends_on: ['redis']

  router:
    image: 'afloury/smart-scavenger-hunt:router'
    ports: ['5001:80/tcp']
    networks: ['default', 'smart-scavenger-hunt']

  location-restriction:
    image: 'afloury/smart-scavenger-hunt:location-restriction'
    ports: ['5002:80/tcp']
    networks: ['default', 'smart-scavenger-hunt']
    depends_on: ['redis', 'lrid-generator']

  supervision:
    image: 'afloury/smart-scavenger-hunt:supervision'
    ports: ['5003:80/tcp']
    networks: ['default', 'smart-scavenger-hunt']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: ['redis', 'lrid-generator']

  orchestrator:
    image: 'afloury/smart-scavenger-hunt:orchestrator'
    networks: ['default', 'smart-scavenger-hunt']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: ['redis', 'lrid-generator']

networks:
  smart-scavenger-hunt:
    external:
      name: smart-scavenger-hunt

  # Todo: Ajouter un traefik ou un haproxy plutôt que de taper directement dans les ports des conteneurs
