version: '3'

services:
  router:
    image: 'smart-scavenger-hunt:router'
    ports: ['5001:80/tcp']
    networks: ['smart-scavenger-hunt']

  location-restriction:
    image: 'smart-scavenger-hunt:location-restriction'
    ports: ['5002:80/tcp']
    networks: ['smart-scavenger-hunt']

  orchestrator:
    image: 'smart-scavenger-hunt:orchestrator'
    ports: ['5003:80/tcp']
    networks: ['smart-scavenger-hunt']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']

networks:
  smart-scavenger-hunt:
    external:
      name: smart-scavenger-hunt

  # Todo: Ajouter un traefik ou un haproxy plutôt que de taper directement dans les ports des conteneurs
