source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Smart-Scavenger-Hunt-iOS' do
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON'
    pod 'KeychainSwift', '~> 10.0'
end
